LOGGER_NAME = "pulse"

# API limits
API_RATE_LIMIT = 100
API_RATE_LIMIT_SECONDS = 60

# Redis Streams / Consumer Groups
CONSUMER_GROUP_NAME = "event_processors"
STREAM_MAX_LENGTH = 100000
CONSUMER_GROUP_EXISTS_ERROR = "BUSYGROUP"
